insert into offices values('VCAA' ,'Office of the Vice Chancellor for Academic Affairs','academics', ''  ,'','VCAA');
insert into offices values('Math' ,'Mathematics Department','department','','','CNSM');
insert into offices values('Bio' ,'Biology Department','department', '','','CNSM');
insert into offices values('GS' ,'Graduate School','college', '','','');
insert into offices values('OSA' ,'Office of Student Affairs','academics', '','','');
insert into offices values('OPESCA' ,'Office of Physical Education, Sports and Cultural Affairs','academics', '','','');
insert into offices values('REGISTRAR' ,'Campus Registrar','academics', '','','');
insert into offices values('AO' ,'Admission Office','academics', '','','');
insert into offices values('LIB' ,'University Library','academics', '','','');
insert into offices values('HRMO' ,'Human Resource Management Office','administrative', '','','');
insert into offices values('SMO' ,'Supply Management Office','administrative', '','','VCAF');
insert into offices values('Fil' ,'Filipino Department','department', '','','CSSH');
insert into offices values('Dorm' ,'Dormitories and Housing Management','administrative', '','','');
insert into offices values('CSO' ,'Civil Service Office','administrative', '','','');
insert into offices values('Agro' ,'Agronomy Department','department', '','','COAgri');
insert into offices values('AgEng' ,'Agricultural Engineering','department','', '','COAgri');
insert into offices values('AnSci' ,'Animal Science Department','department', '','','COAgri');
insert into offices values('EconMM' ,'Economics, Marketing and Management Department','department', '','','CBAA');
insert into offices values('Acctc' ,'Accountancy Department','department', '','','CBAA');
insert into offices values('EEd' ,'Elementary Education','department', '','','COEd');
insert into offices values('SEd' ,'Secondary Education','department', '','','COEd');
insert into offices values('SHS' ,'Senior High School Department','department', '','','COEd');
insert into offices values('PPO' ,'Physical Plant Office','administrative', '','','');
insert into offices values('CEngr' ,'Civil Engineering Department','department', '','','COEngr');
insert into offices values('EEngr' ,'Electrical Engineering Department','department', '','','COEngr');
insert into offices values('MEngr' ,'Mechanical Engineering Department','department', '','','COEngr');
insert into offices values('EngrTech' ,'Engineering Technology Department','department', '','','COEngr');
insert into offices values('AquaC' ,'Aquaculture Department','department', '','','COF');
insert into offices values('MBio' ,'Fish Processing and Marine Biology Department','department', '','','COF');
insert into offices values('Eng' ,'English Department','department', '','','CSSH');
insert into offices values('Socio' ,'Sociology Department','department', '','','CSSH');
insert into offices values('PolSci' ,'Political Science Department','department', '','','CSSH');
insert into offices values('IsStud' ,'Islamic Studies Department','department', '','','CSSH');
insert into offices values('His' ,'History Department','department', '','','CSSH');
insert into offices values('CETD' ,'CET Department','department', '','','COEd');
insert into offices values('VCAF' ,'Office of the Vice Chancellor for Administration and Finances','administrative', '','','VCAF');
insert into offices values('CSSH' ,'College of Social Sciences and Humanities','college', '','','VCAA');
insert into offices values('COEd' ,'College of Education','college', '','','');
insert into offices values('COAgri' ,'College of Agriculture','college', '','','');
insert into offices values('COF' ,'College of Fisheries','college', '','','');
insert into offices values('COL' ,'College of Law Extension Class','college', '','','');
insert into offices values('ECEngr' ,'Electronic and Communication Engineering Department','department', '','','COEngr');
insert into offices values('MSU-CC' ,'Computer Center','administrative', '','','VCAF');
insert into offices values('AccCenter' ,'V.C.A.A. Accreditation/Quality Assurance','academics', '','','VCAA');
insert into offices values('AcctO' ,'Accounting Office','admnistrative', '','','');
insert into offices values('Budget' ,'Budget Office','administrative', '','','');
insert into offices values('CNSM' ,'College of Natural Sciences and Mathematics','college', '','','VCAA');
insert into offices values('COEngr' ,'College of Engineering','college', '','','');
insert into offices values('IT-Physics' ,'Information Technology and Physics Department','department', '','','CNSM');
insert into offices values('OC' ,'Office of the University Chancellor','administrative', '','','OC');
insert into offices values('PROC' ,'Procurement Office','administrative', '','','VCAF');
insert into offices values('CBAA' ,'College of Business Administration and Accountancy','college', '','','');

