from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^profile/$', views.profile, name = 'profile'),
    url(r'^updateProfilePic/$', views.updateProfilePic, name = 'updateProfilePic'),
    url(r'^search/$', views.search, name = 'search'),
    url(r'^create_pr/$', views.create_pr, name = 'create_pr'),
    url(r'^createPRFromRef/$', views.createPRFromRef, name = 'createPRFromRef'),
    url(r'^pr/$', views.pr, name = 'pr'),
    url(r'^accounts/$', views.accounts, name = 'accounts'),
    url(r'^accounts/par_details/$', views.parDetails, name = 'parDetails'),
    url(r'^notifs/$', views.notifications, name = 'notifications'),
    url(r'^pr/pr_details/$', views.prDetails, name = 'prDetails'),
    url(r'^pr/(?P<refData>\w+)/details/$', views.prDetails_WithRef, name = 'prDetails_WithRef'),
    url(r'^addpr/$', views.addPr, name = 'addPr'),
    url(r'^addris/$', views.addRIS, name = 'addRIS'),
    url(r'^displayReqDetails/$', views.displayReqDetails, name = 'displayReqDetails'),
    url(r'^abstract_details/$', views.abstract, name = 'abstract'),
    url(r'^displayPARDetails/$', views.displayPARDetails, name = 'displayPARDetails'),
    url(r'^updateAbstract/$', views.updateAbstract, name = 'updateAbstract'),
    url(r'^generatePDF/$', views.generatePDF, name = 'generatePDF'),
    url(r'^generatePRDocument/$', views.generatePRDocument, name = 'generatePRDocument'),
    url(r'^generatePRDocument/(?P<refData>\w+)/$', views.generatePRDocumentFromRef, name = 'generatePRDocumentFromRef'),
    url(r'^testingLang/$', views.testingLang, name = 'testingLang'),
    url(r'^checkPass/$', views.checkPass, name = 'checkPass'),
    url(r'^changePass/$', views.changePass, name = 'changePass'),
    url(r'^approvalInfo/$', views.approvalInfo, name = 'approvalInfo'),
    url(r'^canvassInfo/$', views.canvassInfo, name = 'canvassInfo'),
    url(r'^procInfo/$', views.procInfo, name = 'procInfo'),
    url(r'^delInfo/$', views.delInfo, name = 'delInfo'),
    url(r'^receiveInfo/$', views.receiveInfo, name = 'receiveInfo'),
    url(r'^cancelPR/$', views.cancelPR, name = 'cancelPR'),
    url(r'^generateACDocument/$', views.generateACDocument, name = 'generateACDocument'),
    url(r'^inquire/$', views.inquire, name = 'inquire'),
    url(r'^accounts/office/$', views.theOffDetails, name = 'theOffDetails'),
    url(r'^ris/$', views.ris, name = 'ris'),
    url(r'^ris/details/$', views.risDetails, name = 'risDetails'),
    url(r'^displayRISDetails/$', views.displayRISDetails, name = 'displayRISDetails'),
    url(r'^findItems/$', views.findItems, name = 'findItems'),
    url(r'^findSupplyItems/$', views.findSupplyItems, name = 'findSupplyItems'),
    url(r'^getItemDetails/$', views.getItemDetails, name = 'getItemDetails'),
    url(r'^getSupplyAvailability/$', views.getSupplyAvailability, name = 'getSupplyAvailability'),
    url(r'^generateRISDocument/$', views.generateRISDocument, name = 'generateRISDocument'),
    #url(r'^output/$', views.return_data),
    ]
 
