# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
