from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^profile/$', views.profile, name = 'profile'),
    url(r'^add_bid/$', views.addBid, name = 'addBid'),
    url(r'^bids/$', views.bid, name = 'bid'),
    url(r'^add_quotation/$', views.addQuotation, name = 'addQuotation'),
    url(r'^add_quotation_new/$', views.addQuotationNew, name = 'addQuotationNew'),
    url(r'^quotations/$', views.quotation, name = 'quotation'),
    url(r'^add_abstract/$', views.addAbstract, name = 'addAbstract'),
    url(r'^add_abstract_new/$', views.addAbstractNew, name = 'addAbstractNew'),
    url(r'^abstract/$', views.abstract, name = 'abstract'),
    url(r'^create_po/$', views.createPO, name = 'createPO'),
    url(r'^create_po_from_abstract/$', views.newPOFromABS, name = 'newPOFromABS'),
    url(r'^po/$', views.po, name = 'po'),
    url(r'^add_contract/$', views.addContract, name = 'addContract'),
    url(r'^contract/$', views.contract, name = 'contract'),
    url(r'^pr/$', views.allPR, name = 'allPR'),
    url(r'^pr/(?P<refData>\w+)/details/$', views.prDetails, name = 'prDetails'),
    url(r'^pr/departments/$', views.departmentPR, name = 'departmentPR'),
    url(r'^pr/list/$', views.prList, name = 'prList'),
    url(r'^number_a_pr/$', views.numPR, name = 'numPR'),
    url(r'^notifs/$', views.displayNotif, name = 'displayNotif'),
    url(r'^number_a_pr/pr_details/$', views.prForNumDetails, name = 'prForNumDetails'),
    url(r'^numtheReq/$', views.numtheReq, name = 'numtheReq'),
    url(r'^prListDetails/$', views.prListDetails, name = 'prListDetails'),
    url(r'^addReqQuotation/$', views.addReqQuotation, name = 'addReqQuotation'),
    url(r'^getSupplierDetails/$', views.getSupplierDetails, name = 'getSupplierDetails'),
    url(r'^findComp/$', views.findComp, name = 'findComp'),
    url(r'^findRepComp/$', views.findRepComp, name = 'findRepComp'),
    url(r'^getPRItems/$', views.getPRItems, name = 'getPRItems'),
    url(r'^getReqComp/$', views.getReqComp, name = 'getReqComp'),
    url(r'^getReqQItems/$', views.getReqQItems, name = 'getReqQItems'),
    url(r'^addAbstractOfCanvass/$', views.addAbstractOfCanvass, name = 'addAbstractOfCanvass'),
    url(r'^addPO/$', views.addPO, name = 'addPO'),
    url(r'^po/pendingPO/$', views.pendingPO, name = 'pendingPO'),
    url(r'^po/details/$', views.poCompleteDetails, name = 'poCompleteDetails'),
    url(r'^po/(?P<refData>\w+)/details/$', views.displayPODetails, name = 'displayPODetails'),
    url(r'^abstract/(?P<refData>\w+)/details/$', views.abcCompleteDetailsFromRef, name = 'abcCompleteDetailsFromRef'),
    url(r'^quotations/(?P<refData>\w+)/details/$', views.rqCompleteDetailsFromRef, name = 'rqCompleteDetailsFromRef'),
    url(r'^abstract/details/$', views.abcCompleteDetails, name = 'abcCompleteDetails'),
    url(r'^quotations/details/$', views.rqCompleteDetails, name = 'rqCompleteDetails'),
    url(r'^validatePO/$', views.validatePO, name = 'validatePO'),
    url(r'^addPObyAbs/$', views.addPObyAbs, name = 'addPObyAbs'),
    url(r'^getEmployeeData/$', views.getEmployeeData, name = 'getEmployeeData'),
    url(r'^suppliers/$', views.suppliers, name = 'suppliers'),
    url(r'^suppliers/details$', views.suppCompleteDetails, name = 'suppCompleteDetails'),
    url(r'^generateRQDocument/$', views.generateRQDocument, name = 'generateRQDocument'),
    url(r'^generatePODocument/$', views.generatePODocument, name = 'generatePODocument'),
    url(r'^generatePODocumentFromAbs/(?P<refData>\w+)/$', views.generatePODocumentFromAbs, name = 'generatePODocumentAbs'),
    url(r'^notifs/(?P<refData>\w+)/$', views.notifications, name = 'notifications'),



    ]
 
